apiVersion: apps/v1
kind: Deployment
metadata:
  name: planet9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planet9
  template:
    metadata:
      labels:
        app: planet9
    spec:
      containers:
      - name: planet9
        image: neptunesoftware/planet9:<version>
        resources:
          requests:
            cpu: 1000m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 1Gi
        ports:
        - containerPort: 8080
          name: planet9
---
apiVersion: v1
kind: Service
metadata:
  name: planet9
spec:
  ports:
  - port: 8080
  selector:
    app: planet9
  type: LoadBalancer
