apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: planet9
spec:
  serviceName: planet9
  replicas: 1
  selector:
    matchLabels:
      app: planet9
  template:
    metadata:
      labels:
        app: planet9
    spec:
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: azure-managed-disk
      containers:
        - name: planet9
          image: neptunesoftware/planet9:mssql
          resources:
            requests:
              cpu: 100m
              memory: 0.5Gi
            limits:
              cpu: 1000m
              memory: 1Gi
          ports:
            - containerPort: 8080
              name: planet9
          env:
            - name: DB_TYPE
              value: mssql
            - name: DB_MSSQL_HOST
              value: localhost
            - name: DB_MSSQL_PORT
              value: "1433"
            - name: DB_MSSQL_USER
              value: "someuser"
            - name: DB_MSSQL_PASSWORD
              value: "somepassword"
            - name: DB_MSSQL_SCHEMA
              value: "planet9"
            - name: DB_MSSQL_DBNAME
              value: "tenant-1"
            - name: P9_MODULES_PATH
              value: "/home/planet9/ext-disk"
          volumeMounts:
            - mountPath: "/home/planet9/ext-disk"
              name: volume
---
apiVersion: v1
kind: Service
metadata:
  name: planet9
spec:
  ports:
    - port: 8080
  selector:
    app: planet9
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 30Gi